# Change these first
owner: flashskynews # Your GitHub organization or username, where this repository lives
repo: statuspage # The name of this repository

sites:
  - name: Tyler
    check: "tcp-ping"
    url: tyler.kay0.net
    port: $pingport
  - name: Papatastisch
    check: "tcp-ping"
    url: papatastisch.kay0.net
    port: $pingport
  - name: Cat Girl
    check: "tcp-ping"
    url: $catgirlsrv
    port: $pingport
  - name: Posty
    check: "tcp-ping"
    url: posty.kay0.net
    port: $pingport
  - name: Rocky
    check: "tcp-ping"
    url: rocky.kay0.net
    port: $pingport
  - name: Ariana
    check: "tcp-ping"
    url: ariana.kay0.net
    port: $pingport
  - name: Scott
    check: "tcp-ping"
    url: scott.kay0.net
    port: $pingport
  - name: MBeezy
    check: "tcp-ping"
    url: mbeezy.kay0.net
    port: $pingport
  - name: Freddy
    check: "tcp-ping"
    url: freddy.kay0.net
    port: $pingport

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.kay0.net
  # baseUrl: /your-repo-name
  logoUrl: https://i.kay0.io/favicon/kay0-transparent.png
  name: kay0.net
  introTitle: "Servers & Programs"
  introMessage: Status page for every important server and service I provide or maintain.
  navbar:
    - title: Status
      href: /
    - title: GitHub (Source)
      href: https://github.com/upptime/upptime
   favicon: https://i.kay0.io/favicon/android-chrome-512x512.png
  
  commitMessages:
    commitAuthorName: "Uptime Bot"
    commitAuthorEmail: "uptimebot@kay0.io"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
